name: Generate Snake Animation

on:
  schedule:
    # Runs at 2am UTC every day
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Step 1: Checks out your repository
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 2: Runs the snake generator action
      - uses: platane/snk@v3
        with:
          github_user_name: divit-aggarwal
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg?palette=github-dark
            
      # Step 3: Pushes the newly created files to your repository
      - name: Push new snake contribution graphics to the repository
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output
